mywebsite/music/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login,logout
from . import views
app_name='music'
#using genric views
urlpatterns=[
	url(r'^$',views.IndexView.as_view(),name="index"),
    url(r'^(?P<pk>[0-9]+)/$',views.DetailView.as_view(),name="detail"),
    url(r'^album/add/$',views.AlbumCreate.as_view(),name='album-add'),
    url(r'^album/(?P<pk>[0-9]+)/$',views.AlbumUpdate.as_view(),name="album-update"),
     url(r'^album/(?P<pk>[0-9]+)/delete/$',views.AlbumDelete.as_view(),name="album-delete"),
    url(r'^register/$',views.UserFormView.as_view(),name='register'),
        #url(r'^register/$',views.register,name='register'),
        url(r'^login/$',login,{'template_name': 'music/login.html'},name='login'),
        url(r'^logout/$',logout,{'template_name': 'music/logout.html'}, name='logout'),
        url(r'^profile/$',views.profile, name='profile'),
        url(r'^profile/edit/$',views.edit_profile, name='editprofile'),
        url(r'^changepassword/$',views.changepassword, name='changepassword'),
        
        ]
# urlpatterns = [
#     url(r'^$',views.index,name="index"),
#     url(r'^(?P<album_id>[0-9]+)/$',views.detail,name="detail"),
#     url(r'^(?P<album_id>[0-9]+)/favourite/$',views.favourite,name="favourite")
#     ,
    
#     #album_id is the variable we can pass to views

# ]

mywebsite/mywebsite/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.urlpatterns import format_suffix_patterns
from companies import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^music/', include('music.urls')),
    url(r'^stocks/',views.StockList.as_view()),
]
urlpatterns=format_suffix_patterns(urlpatterns)
if settings.DEBUG:
	urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
	urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mywebsite/music/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.db.models.signals import post_save

# Create your models here.
class Album(models.Model):
	artist = models.CharField(max_length=250)
	album_title  = models.CharField(max_length=500)
	genre = models.CharField(max_length=100)
	album_logo = models.FileField(max_length=1000)

	def get_absolute_url(self):
		return reverse('music:detail',kwargs={'pk':self.pk})
	def __str__(self):
		return self.album_title+"-"+self.artist


class Song(models.Model):
	album = models.ForeignKey(Album,on_delete=models.CASCADE)
	#part of album and on_delete cascade means whever we delete album song is itself deleted
	file_type = models.CharField(max_length=10)
	song_title = models.CharField(max_length=250)
	is_fav=models.BooleanField(default=False)
	def __str__(self):
		return self.song_title
class UserProfile(models.Model):
	user=models.OneToOneField(User)
	description=models.CharField(max_length=200,default='')
	city=models.CharField(max_length=50,default='')
	phone=models.IntegerField(default='0')
	
def create_profile(sender,**kwargs):
	if kwargs['created']:
		user_profile=UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile,sender=User)	

mywebsite/music/forms.py
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth.forms import UserChangeForm

class UserForm(forms.ModelForm):
	"""docstring for UserForm"""
	password=forms.CharField(widget=forms.PasswordInput)
	class Meta:
		model=User
		fields=['username','email','password','first_name','last_name']
class EditProfileForm(UserChangeForm):
	class Meta:
		model=User
		fields={'email','first_name','last_name'}
		#exclude={}

mywebsite/music/views.py
#using generic views
from django.views import generic
from .models import Album
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login
#from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import UserChangeForm,PasswordChangeForm
#even after chane password continue session
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.models import User
from django.views.generic import View
from .forms import UserForm,EditProfileForm
class IndexView(generic.ListView):
	template_name='music/index.html'

	def get_queryset(self):
		return Album.objects.all()

class DetailView(generic.DetailView):
	model=Album
	template_name='music/detail.html'

class AlbumCreate(CreateView):
	model=Album
	fields='__all__'

class AlbumUpdate(UpdateView):
	model=Album
	fields='__all__'

class AlbumDelete(DeleteView):
	model=Album
	success_url=reverse_lazy('music:index')
# def register(request):
# 	if request.method=='POST':
# 		form=UserCreationForm(request.POST)
# 		if form.is_valid():
# 			form.save()
# 			return redirect('/music')
# 	else:
# 		form=UserCreationForm()

# 		args={'form':form}
# 		return render(request, 'music/registration_form.html',args)
def profile(request):
	args={'user':request.user}
	return render(request,'music/profile.html',args)

def edit_profile(request):
		if request.POST:
			form=EditProfileForm(request.POST,instance=request.user)

			if form.is_valid():
				form.save()
				return render(request,'music/profile.html')


		else:
			form=EditProfileForm(instance=request.user)
			args={'form':form}
		return render(request,'music/editprofile.html',args)


def changepassword(request):
	if request.POST:
			form=PasswordChangeForm(data=request.POST,user=request.user)

			if form.is_valid():
				form.save()
				update_session_auth_hash(request,form.user)
				return render(request,'music/profile.html')
			else:
				return render(request,'music/changepassword.html',{'form':form})


	else:
		form=PasswordChangeForm(user=request.user)
		args={'form':form}
		return render(request,'music/changepassword.html',args)





class UserFormView(View):
	form_class=UserForm
	template_name='music/registration_form.html'
	#get method to give just a blank form so,none is passed,but request.post in post method
	def get(self,request):
		form=self.form_class(None)
		return render(request,self.template_name,{'form':form})

	def post(self,request):
			form=self.form_class(request.POST)

			if form.is_valid():
				user=form.save(commit=False)
				username=form.cleaned_data['username']

				password=form.cleaned_data['password']
				user.set_password(password)
				user.save()

				user=authenticate(username=username,password=password)
				if user is not None:
					if user.is_active:
						login(request,user)
						return redirect('music:index')

			return render(request,self.template_name,{'form':form})

# from django.shortcuts import render,get_object_or_404
# from django.http import HttpResponse
# from django.http import Http404
# from .models import Album,Song
# #connecting to database
# # def index(request):
# # 	a=Album.objects.all()
# # 	context={
# # 	'a':a
# # 	}
# # 	# html=""
# # 	# for b in a:
# # 	# 	url='/music/'+str(b.id)+'/'
# # 	# 	html+='<a href="'+url+'">'+str(b.id)+b.album_title+'</a><br>'
# # 	return render(request,"music/index.html",context)
# # def detail(request,album_id):
# # 	#album_id is the variable from urls.py
# # 	# try:
# # 	# 	z=Album.objects.get(pk=album_id)
# # 	# except Album.DoesNotExist:
# # 	# 	raise Http404("Album does not exist")
# # 	#all above can be written in 1 single code below by just adding in import
# # 	album=get_object_or_404(Album,pk=album_id)
# # 	return render(request,'music/detail.html',{'album':album})

# # def favourite(request,album_id):
# # 	album=get_object_or_404(Album,pk=album_id)
# # 	try:
# # 		r=request.POST['song']
# # 		print(r)
# # 		selected_song=album.song_set.get(pk=request.POST['song'])
# # 	except (KeyError,Song.DoesNotExist):
# # 		return render(request,'music/detail.html',{'album':album,'error_message':"you did not select a valid song"})
# # 	else:

# # 		print("suraj")
# # 		selected_song.is_fav=True

# # 		selected_song.save()


# # 		return render(request,"music/detail.html",{'album':album})

mywebsite/music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title%}Add a new album{% endblock %}
{% block albums_active%}active{% endblock %}


{%block body%}
<div class="container-fluid">
	<div class="row">
		<div class="col-sm-12 col md-7">
			<div class="panel panel-default">
				<div class="panel-body">
					<form class="form-horizontal" action="" method="POST" enctype="multipart/form-data">
						{%csrf_token%}
						{%include 'music/form-template.html'%}
						<div class="form-group">
							<div class="col-sm-offset-2 col-sm-10">
								<button type="submit" class="btn btn-success">Submit</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
	

{% endblock %}

mywebsite/music/templates/music/base.html
<!DOCTYPE html>
<html lang='en'>
<head>
	<title>{% block title%}Music_Infos.com
{% endblock %}
</title>
	<!--loads path of static files -->
	{% load staticfiles%}
<link rel="stylesheet" type="text/css" href="{%static 'music/bootstrap/css/bootstrap.min.css'%}"/>
<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Satisfy"/>

<link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="{%static 'music/bootstrap/js/bootstrap.min.js'%}"></script>
</head>
<body>

<nav class="navbar navbar-inverse">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="{% url 'music:index'%}">Music_Infos.com</a>
		</div>

		<!-- items-->
		<div class="container">
		<div class="collapse navbar-collapse" id="topNavBar">
			{%if user.is_authenticated%}
			<ul class="nav navbar-nav">
				<li class="">
				<a href="{% url 'music:index'%}">
				<span class="glyphicon glyphicon-cd" aria-hidden="true"></span> Albums
				</a>
				</li>
				<li class="">
				<a href="#">
				<span class="glyphicon glyphicon-music"></span> Songs
				</a>
				</li>
			</ul>
			<form class="navbar-form navbar-left" role="search" method="get" action="#">
				<div class="form-group">
					<input type="text" class="form-control" name="q" value="">
				</div>
				<button type="submit" class="btn btn-default">Search
				</button>
			</form>
			<ul class="nav navbar-nav navbar-right">
				<li class="">
				<a href="{% url 'music:profile'%}">
				<span class="glyphicon glyphicon-user" aria-hidden="true"></span> MyProfile
				</a>
				</li>
				<li class="">
				<a href="{% url 'music:album-add'%}">
				<span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add Albums
				</a>
				</li>
				<!-- <li class="">
				<a href="{% url 'music:register'%}">
				<span class="glyphicon glyphicon-on" aria-hidden="true"></span>Signup
				</a>
				</li>
				<li class="">
				<a href="{% url 'music:login'%}">
				<span class="glyphicon glyphicon-on" aria-hidden="true"></span>Login
				</a>
				</li> -->


				<li class="">
				<a href="{% url 'music:logout'%}">
				<span class="glyphicon glyphicon-off" aria-hidden="true"></span>Logout
				</a>
				</li>
			</ul>

			{%else%}
			<ul class="nav navbar-nav navbar-right">
				<li class="">
				<a href="{% url 'music:register'%}">
				<span class="glyphicon glyphicon-hand-up" aria-hidden="true"></span>Signup
				</a>
				</li>
				<li class="">
				<a href="{% url 'music:login'%}">
				<span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>&nbsp;Login
				</a>
				</li>



			</ul>

			{%endif%}
			</div>
			</div>
			</div>
			</nav>







{% block body%}
{% endblock %}
</body>
<footer class="bottom">
	{% block footer%}

{% endblock %}
</footer>
</html>

mywebsite/music/templates/music/changepassword.html
{% extends 'music/base.html' %}
{%block title%}
<title>Profile</title>
{%endblock%}
{%block body%}
<div class="container">
<form method="POST">
{%csrf_token%}
{{form.as_p}}

<button type="submit">Submit</button>
</form>
</div>
{%endblock%}

mywebsite/music/templates/music/demo.html
<script type="text/javascript">
	
function demo()

{

var data= document.getElementById('name').value;

if (data.length==null) {

var error="feild should not be null";


alert(error);


}




</script>



<body>


<input type="text" id="name">

<input type="submit" onclick="demo();">
</body>

mywebsite/music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title%}
Song_Details
{% endblock %}

{%block body%}
	<img src="{{album.album_logo.url}}">
	<h1>{{album.album_title}}</h1>
	<h3>{{album.artist}}</h3>

	<ul>
	{% for song in album.song_set.all%}	
		<li>{{ song.song_title }}{{song.file_type}}</li>
	{%endfor%}
	</ul>
	{% endblock %}
	
	<!-- <form action="{% url 'music:favourite' album.id %}" method="POST">
		{% csrf_token %}
		{%for song in album.song_set.all %}
		<input type="radio" id="song{{ forloop.counter}}" name="song" value="{{song.id}}"/>
		<label for="song{{ forloop.counter}}">
			{{ song.song_title}}
			{%if song.is_fav %}
		<img src="http://i.imgur.com/b9b13Rd.png"/>
			{%endif%}
		</label><br>
		
	{%endfor%}
	<input type="submit" value="Favourite">

	 </form> -->

mywebsite/music/templates/music/editprofile.html
{% extends 'music/base.html' %}
{%block title%}
<title>Profile</title>
{%endblock%}
{%block body%}
<div class="container">
<form method="POST">
{%csrf_token%}
{{form.as_p}}

<a href="{%url 'music:changepassword'%}">Click here to change your Password</a>
<br>
<button type="submit">Submit</button>
</form>
</div>
{%endblock%}

mywebsite/music/templates/music/form-template.html
{%for field in form%}
<div class="form-group">
	
		<div class="col-sm-offset-2 col-sm-10">
			<span class="text-danger small">{{field.errors}}</span>

		</div>
		<label class="control-label col-sm-2">{{field.label_tag}}</label>
		<div class="col-sm-10">{{field}}</div>
</div>
{%endfor%}

mywebsite/music/templates/music/index.html
{% extends 'music/base.html' %}
{% block title%}MusicInfos.com
{% endblock %}
{%block body%}
	{%if object_list%}
		
		<div class="container">
		
			{% for b in object_list %}
			
			
			<div class="col-md-4">
			
			<!-- <div class="thumbnail" style="height:100px width:100px">-->
			<div class="well well-md">
			<a href="{% url 'music:detail' b.id %}"><img src="{{b.album_logo.url}}" class="img-rounded" alt="Image Not Available" width="300" height="300">
			</a><h2>{{b.album_title}}</h2><h4>{{b.artist}}</h4>
			<br>
			<a href="{% url 'music:detail' b.pk %}" class="btn btn-primary btn-sm"> VIew Details</a>

			<form action="{%url 'music:album-delete' b.id%}" method="POST" style="display: inline;">
			{%csrf_token%}<button type="submit" class="btn btn-default btn-sm">
			<span class="glyphicon glyphicon-trash"></span>
			</button>
			</form>
			<a href="#" class="btn btn-default btn-sm btn-favourite">
			<span class="glyphicon glyphicon-star {% if b.is_fav %} active{%endif%}"></span>
			</a>
			<!-- </div>
			</div> -->
			</div>
			</div>
			

			

			

			


			{% endfor %}
		</div>
			

	{%else%}
		<h3> You dont have any albums</h3>
	{%endif%}
{%endblock%}

mywebsite/music/templates/music/login.html
{% extends 'music/base.html'%}
{% block title%}login Page
{% endblock %}
{%block body%}
<div class="container">
	<h1>Welcome</h1>
	<p>You can login here</p>
	<h2>login</h2>
	<form id="userform" method="post">
	$(document).on('submit',#userform',funtion(e)
	{


	e.preventDefault();


		

		{% csrf_token %}
		<!--form as paragraph-->
		{{form.as_p}}
	<button type="submit">Login</button>	

	</form>
</div>
{%endblock%}

mywebsite/music/templates/music/logout.html
{% extends 'music/base.html'%}
{% block title%}logout Page
{% endblock %}
{%block body%}
<div class="container">
	<h3>You have logged out</h2>
	<p>Please login  to continue</p>
	
</div>
{%endblock%}

mywebsite/music/templates/music/profile.html
{% extends 'music/base.html' %}
{%block title%}
<title>Profile</title>
{%endblock%}
{%block body%}
<div class="container">
<h1>Here is your Profile</h1>
<p>Username:{{user}}
<br>Firstname:{{user.first_name}}
<br>Last name:{{user.last_name}}

</p>
<a href="{%url 'music:editprofile'%}">Click here to edit your profile</a>
</div>
{%endblock%}

mywebsite/music/templates/music/registration_form.html
{% extends 'music/base.html' %}
{% block title%}Register{% endblock %}



{%block body%}
<div class="container-fluid">
<!-- <h1>Register Here</h1>
<form method="POST">
{% csrf_token%}
{{form.as_p}}
								<button type="submit" class="btn btn-success">Submit</button> -->
</form>
<h1>Register Here</h1>
	<div class="row">
		<div class="col-sm-12 col md-7">
			<div class="panel panel-default">
				<div class="panel-body">
				<h3>Create a new account</h3>
					<form class="form-horizontal" action="" method="POST" enctype="multipart/form-data">
						{%csrf_token%}
						{%include 'music/form-template.html'%}
						<div class="form-group">
							<div class="col-sm-offset-2 col-sm-10">
								<button type="submit" class="btn btn-success">Submit</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
	

{% endblock %}